version: '3'
services:
  app:
    network_mode: host
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SIGN_KEY: ${JWT_SIGN_KEY}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      OSS_ENDPOINT: ${OSS_ENDPOINT}
      OSS_ACCESS_KEY_ID: ${OSS_ACCESS_KEY_ID}
      OSS_ACCESS_KEY_SECRET: ${OSS_ACCESS_KEY_SECRET}
      OSS_BUCKET: ${OSS_BUCKET}
    image: "2021-hackathon"
    container_name: "2021-hackathon"
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /root/docker/save/hackathon/logs:/data/logs
      - /etc/share/nginx/html/picture:/etc/share/nginx/html/picture