name: 2021-hackathon-backend-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Rsync-deploy
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          SERVER_IP: ${{ secrets.SSH_HOST }}
          SERVER_PORT: "22"
          USERNAME: ${{ secrets.SSH_USERNAME }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

          ARGS: "-a -z --delete"
          FOLDER: ./
          SERVER_DESTINATION: /root/project-be/2021-hackathon/

      - name: Start-server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /root/project-be/2021-hackathon/
            ./run.sh